import os, re, imp

Import('env')

if GetOption('win64'):
    from utils import win_build as c
else:
    from utils import linux_build as c

sourcepaths = c.sourcepaths
libpaths    = c.libpaths
cppflags    = c.cppflags
linkflags   = c.linkflags
libOther    = c.libOther
target      = '#/bin/main' + c.targetSuffix

cppflags.extend(['-O0', '-g','-std=c++11'])
cppflags.extend(['-Wall', '-Wextra'])

cppFiles = [Glob('main.cpp') +
            Glob('*/*.cpp') +
            Glob('*/*/*.cpp')]
app = env.Program(target, cppFiles,
                  LIBPATH   = libpaths,
                  CPPPATH   = sourcepaths,
                  CPPFLAGS  = cppflags,
                  LINKFLAGS = linkflags,
                  LIBS      = libOther)
Default(app)
