import os, re, imp

Import('env')

if GetOption('win64'):
    from utils import win_build as c
else:
    from utils import linux_build as c

c.cppflags.extend(['-O0', '-g','-std=c++11'])
c.cppflags.extend(['-Wall', '-Wextra'])

target   = '#/bin/Hello_SDL_ttf' + c.targetSuffix
cppFiles = [Glob('main.cpp') +
            Glob('*/*.cpp') +
            Glob('*/*/*.cpp')]

app = env.Program(target, cppFiles,
                  LIBPATH   = c.libpaths,
                  CPPPATH   = c.sourcepaths,
                  CPPFLAGS  = c.cppflags,
                  LINKFLAGS = c.linkflags,
                  LIBS      = c.libs)
Default(app)
